---
title: "graphs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{graphs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(tidyverse)
library(skimr)
library(lubridate)
library(here)
library(janitor)
library(socviz)
library(ggrepel)
library(showtext)
library(hrbrthemes)
library(magick)
# install.packages("paletteer")
library(paletteer)
library(ggthemes)
library(patchwork)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  fig.path = "inst/img/",
  tidy = FALSE,
  collapse = TRUE,
  comment = "#>",
  dev = "ragg_png",
  dpi = 320,
  out.width = "80%",
  fig.width = 6.5,
  fig.asp = 0.618,
  fig.retina = 2,
  fig.align = 'center'
)
# knitr::opts_knit$set(root.dir = '/Users/mjfrigaard/Dropbox/@projects/high-priority/@apps/dmwt/')
# set width
options(width = 60, max.print = 300)
```

```{r pkg, eval=FALSE}
library(dmwt)
```

# Graphs

Load the data (`ExOffndrsComplete`) from the `data-raw/` folder. 


```{r import-ExOffndrsComplete}
ExOffndrsComplete <- vroom::vroom(file = "../data-raw/2022-11-01/ExecutedOffendersComplete.csv")
dplyr::glimpse(ExOffndrsComplete)
```

## Create `date` and `race`

Here we format the date variable, create 

```{r ExOffndrsComplete}
ExOffndrsGraphs <- dplyr::mutate(.data = ExOffndrsComplete,
  # format dates 
    date = lubridate::mdy(date),
    year = lubridate::year(date),
    yday = lubridate::yday(date),
    month = lubridate::month(date, label = TRUE),
  # format race
  race = factor(race)) 
dplyr::glimpse(ExOffndrsGraphs)
```


```{r}
ExOffndrsGraphs |> 
  dplyr::count(date, sort = TRUE) |> 
  utils::head(10)
```


## Executions by `year`

Only three days have multiple executions. If we count by `year`, then visualize the number of total executions, we see a spike in the year `2000`. 

```{r top-years}
ExOffndrsGraphs |> 
  dplyr::count(year, sort = TRUE) |> 
  utils::head(10)
```



```{r ggp2_total_exec_year, fig.align='center'}
ggp2_total_exec_year <- ExOffndrsGraphs |> 
  dplyr::count(year, sort = TRUE) |> 
  ggplot(
    aes(
      x = factor(year),
      y = n)) + 
  geom_col(aes(fill = n), 
    position = "stack", 
    show.legend = FALSE) + 
  # viridis::scale_fill_viridis(option = "B", direction = -1) +
  
  
  scale_x_discrete(breaks = c("1980", "1985", "1990", "1995", 
                              "2000", "2005", "2010", "2015", 
                              "2020")) + 
  
  paletteer::scale_fill_paletteer_c("ggthemes::Red") + 
  
  labs(title = "Total Executions in Texas",
    subtitle = paste0("From ", 
      min(ExOffndrsGraphs$year, na.rm = TRUE), " to ", 
      max(ExOffndrsGraphs$year, na.rm = TRUE)),
    x = "Year", y = "Executions") + 
  theme_minimal()
ggp2_total_exec_year
```



```{r ggp2_race_year_cols}
ggp2_race_year_cols <- ExOffndrsGraphs %>%
  # remove 'Other'
  dplyr::filter(race != "Other") %>% 
  dplyr::group_by(race, year) %>% 
      dplyr::summarise(
            ex_race_by_year = sum(n())) %>% 
    dplyr::arrange(desc(ex_race_by_year)) %>% 
  dplyr::ungroup() |> 
  ggplot(
    aes(y = ex_race_by_year,
        x = year,
        fill = race)) +
  ggplot2::geom_col(aes(fill = race),
    size = 1.5, show.legend = FALSE) +
  ggplot2::scale_x_continuous(
    breaks = c(1980, 2000, 2015)) +
  ggplot2::scale_fill_manual(
    values = c("1980", "2000", "2015"), 
    breaks = c("1980", "2000", "2015")) +
  # ggplot2::scale_fill_manual(
  #   values = c("1980", "1990", "2000", "2010", "2020")) + 
  paletteer::scale_fill_paletteer_d("ggthemes::wsj_dem_rep", 
    direction = 1) +
  ggplot2::facet_wrap(. ~ race, ncol = 3, nrow = 1) +
  ggplot2::labs(
    title = "Total Executions in Texas by Race",
    subtitle = paste0("From ", min(ExOffndrsGraphs$year, na.rm = TRUE), " to ", 
      max(ExOffndrsGraphs$year, na.rm = TRUE)),
    x = "Year", y = "Executions") +
  ggplot2::theme_minimal()
ggp2_race_year_cols
```

```{r by_year_labels}
by_year_labels <- ExOffndrsGraphs %>%
  # remove 'Other'
  dplyr::filter(race != "Other") %>% 
  dplyr::group_by(race, year) %>% 
      dplyr::summarise(
            ex_race_by_year = sum(n())) %>% 
    dplyr::arrange(desc(ex_race_by_year)) %>% 
  dplyr::ungroup() |> 
  dplyr::group_by(race) |> 
  dplyr::slice_max(ex_race_by_year) |> 
  dplyr::mutate(
    label = paste0(ex_race_by_year, " ", race, " executions in ", year)
  )
by_year_labels
```

```{r ggp2_max_race_year_line}
ggp2_max_race_year_line <- ExOffndrsGraphs %>%
  # remove 'Other'
  dplyr::filter(race != "Other") %>%
  dplyr::group_by(race, year) %>%
  dplyr::summarise(ex_race_by_year = sum(n())) %>%
  dplyr::arrange(desc(ex_race_by_year)) %>%
  dplyr::ungroup() |>
  ggplot(aes(x = year,
    y = ex_race_by_year)) +
  # add the lines
  ggplot2::geom_line(aes(color = race),
    size = 1.3,
    show.legend = FALSE) +
  ggrepel::geom_label_repel(
    data = by_year_labels,
    aes(
      x = year,
      y = ex_race_by_year,
      label = label
    ),
    color = "black",
    fill = "white",
    size = 3,
    show.legend = FALSE
  ) +
  ggplot2::scale_color_manual(values = c("1980", "1990", "2000", "2010", "2020")) +
  paletteer::scale_color_paletteer_d("ggthemes::wsj_dem_rep", direction = 1) + 
  ggplot2::labs(title = "Peak Executions by Year and Race", 
    subtitle = paste0("From ", 
      min(ExOffndrsGraphs$year, na.rm = TRUE), " to ", 
      max(ExOffndrsGraphs$year, na.rm = TRUE)),
    caption = "Data from Texas Department of Criminal Justice",
    x = "Year", y = "Executions") +
  ggplot2::theme_minimal()
ggp2_max_race_year_line
```


```{r}
library(patchwork)
# ggp2_max_race_year_line
ggp2_total_exec_year / (ggp2_race_year_cols | ggp2_max_race_year_line) +
  patchwork::plot_layout(nrow = 2)
```

